# Generated by Django 5.0.4 on 2026-04-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0001_initial'),
    ]

    operations = [
    ]