# Generated by Django 5.0.4 on 2026-04-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0002_uploadedfile_user'),
        ('knowledge_app', '0003_knowledgemap_topicnode_subtopicnode_noderelationship'),
    ]

    operations = [
    ]
