# Generated by Django 5.0.4 on 2026-04-08 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0004_merge_20260407_1433'),
        ('knowledge_app', '0004_merge_20260407_1448'),
    ]

    operations = [
    ]
