# Generated by Django 6.0.3 on 2026-04-16 21:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_app", "0007_sharemap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShareMap",
            new_name="SharedMap",
        ),
    ]
