# Generated by Django 6.0.3 on 2026-04-18 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_app", "0007_folder_uploadedfile_folder"),
        ("knowledge_app", "0008_rename_sharemap_sharedmap"),
    ]

    operations = []
