# Generated by Django 6.0.3 on 2026-04-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_app", "0007_userprofile"),
        ("knowledge_app", "0009_merge_20260418_0433"),
    ]

    operations = []
