# Generated by Django 6.0.3 on 2026-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_app", "0010_merge_0007_userprofile_0009_merge_20260418_0433"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
